# Generated by Django 3.1.5 on 2021-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model', models.CharField(max_length=12)),
                ('bike_number', models.CharField(max_length=12)),
                ('sevice_type', models.CharField(choices=[('p', 'platinum'), ('g', 'gold')], max_length=1)),
                ('notes', models.CharField(max_length=12)),
                ('service_charge', models.CharField(blank=True, max_length=12)),
                ('submission_date', models.DateTimeField()),
                ('servicing', models.ManyToManyField(blank=True, to='servicing.service')),
            ],
        ),
    ]
